packages:
  - 'packages/typings'
  - 'packages/__tests__/units'
  - 'packages/__tests__/types'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

nodeLinker: hoisted

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/*'
