name: Publish-beta
on:
  push:
    branches:
      - beta

jobs:
  publish:
    name: Publish-beta
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pnpm repo
        uses: 'chlbri/pnpmi-action@main'

      - name: Build
        run: pnpm run build

      - uses: JS-DevTools/npm-publish@v4
        id: publish
        name: Publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          strategy: all
          tag: beta

      - name: Check - updated
        if: ${{ steps.publish.outputs.type }}
        run:
          echo "${{ steps.publish.outputs.name }} Version changed from ${{
          steps.publish.outputs.old-version }} to ${{
          steps.publish.outputs.version }}"

      - name: Check - not updated
        if: ${{ ! steps.publish.outputs.type }}
        run: echo "Remain the same! - ${{ steps.publish.outputs.version }}"
