name: Publish
on:
  push:
    branches:
      - beta
      - canary
      - main
      - master

jobs:
  all:
    uses: chlbri/node-github-actions/.github/workflows/publish.yml@main
    secrets: inherit
    with:
      type:
        ${{ github.ref_name == 'beta' && 'beta' || github.ref_name ==
        'canary' && 'canary' || 'latest' }}
